MODEL:
  META_ARCHITECTURE: "GeneralizedRNAS"
  WEIGHT: "/home/yzhang/FAD/pretrained/R-101.pkl"
  RPN_ONLY: True
  FAD_ON: True
  FCOS_ON: True
  RETINANET_ON: False
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    # normalizing the regression targets with FPN strides
    NORM_REG_TARGETS: True
    # positioning centerness on the regress branch.
    # Please refer to https://github.com/tianzhi0549/FCOS/issues/89#issuecomment-516877042
    CENTERNESS_ON_REG: True
    # using center sampling and GIoU.
    # Please refer to https://github.com/yqyao/FCOS_PLUS
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
  FAD: 
    SEARCH: False 
    CLSTOWER: True 
    NUM_CELLS_CLS: 2 
    NUM_NODES_CLS: 3 
    NUM_CHANNELS_CLS: 96 
    BOXTOWER: True 
    NUM_CELLS_BOX: 2 
    NUM_NODES_BOX: 3 
    NUM_CHANNELS_BOX: 96
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (352,512) #(640, 800)
  MAX_SIZE_TRAIN: 700 #1333
  MIN_SIZE_TEST: 512 #800
  MAX_SIZE_TEST: 700 #1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 6 #16
  CHECKPOINT_PERIOD: 1000
  WARMUP_METHOD: "constant"
