MODEL:
  META_ARCHITECTURE: "GeneralizedRNAS"
  WEIGHT: "/home/yzhang/FAD/pretrained/rfdnet.pth"
  RPN_ONLY: True
  FAD_ON: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "RFDNET"
    FREEZE_CONV_BODY_AT: 2
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    # normalizing the regression targets with FPN strides  
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
  FAD:
    PLOT: True
    SEARCH: True
    CLSTOWER: True
    NUM_CELLS_CLS: 1
    NUM_NODES_CLS: 3
    NUM_CHANNELS_CLS: 96
    BOXTOWER: True
    NUM_CELLS_BOX: 1
    NUM_NODES_BOX: 3
    NUM_CHANNELS_BOX: 96
DATASETS:
  TRAIN: ("coco_2017_train_partition_rate8","coco_2017_val_partition_rate8") #, "coco_2017_val")   #("voc_2012_train", "voc_2012_val") 
  TEST: ("coco_2017_val_partition_rate8",)  #("voc_2012_test",)

INPUT:
  MIN_SIZE_TRAIN: (512,) #(416,)
  MAX_SIZE_TRAIN: 700 #693
  MIN_SIZE_TEST: 512 #800
  MAX_SIZE_TEST: 700 #1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.004 
  WEIGHT_DECAY: 0.0001 
  STEPS: (1875,) #(1875,) (15000, )
  MAX_ITER: 2500  #2500 20000
  CHECKPOINT_PERIOD: 500 #500 2500
  IMS_PER_BATCH: 8 #8 
